/* eslint-disable @typescript-eslint/unbound-method */
import { describe, it, expect, vi, beforeEach, type Mock } from 'vitest';
import { z } from 'zod';
import type { Request, Response, NextFunction } from 'express';
import { Validate } from '../index.js';

const makeRes = () => {
  const res: Partial<Response> = {
    status: vi.fn(),
    json: vi.fn(),
  };
  // Enable chaining: res.status(400).json(...)
  (res.status as Mock).mockReturnValue(res);
  return res as Response;
};

const makeReq = (overrides: Partial<Request> = {}): Request => {
  return overrides as Request;
};

/* ------------------------------- Tests ---------------------------------- */

describe('Validate Middleware', () => {
  const next: NextFunction = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('validate.body', () => {
    const schema = z.object({
      name: z.string(),
      age: z.coerce.number(), // Coercion test
    });

    it('calls next() and updates req.body when validation passes', async () => {
      const req = makeReq({ body: { name: 'Alice', age: '25' } });
      const res = makeRes();

      const middleware = Validate.body(schema);
      await middleware(req, res, next);

      expect(next).toHaveBeenCalledTimes(1);
      // Ensures that Zod's coercion ran and updated the request object
      expect(req.body).toEqual({ name: 'Alice', age: 25 });
      expect(res.status).not.toHaveBeenCalled();
    });

    it('returns 400 and does not call next() on validation failure', async () => {
      const req = makeReq({ body: { age: '25' } });
      const res = makeRes();

      const middleware = Validate.body(schema);
      await middleware(req, res, next);

      expect(next).not.toHaveBeenCalled();
      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.json).toHaveBeenCalledWith({
        success: false,
        // Match the actual string generated by the middleware
        message: expect.stringContaining('expected string'),
      });
    });
  });

  describe('validate.params', () => {
    const schema = z.object({
      id: z.coerce.number(),
    });

    it('calls next() and updates req.params on success', async () => {
      const req = makeReq({ params: { id: '123' } });
      const res = makeRes();

      const middleware = Validate.params(schema);
      await middleware(req, res, next);

      expect(next).toHaveBeenCalledTimes(1);
      expect(req.params).toEqual({ id: 123 });
    });

    it('returns 400 on failure', async () => {
      const req = makeReq({ params: { id: 'not-a-number' } });
      const res = makeRes();

      const middleware = Validate.params(schema);
      await middleware(req, res, next);

      expect(next).not.toHaveBeenCalled();
      expect(res.status).toHaveBeenCalledWith(400);
    });
  });

  describe('validate.query', () => {
    const schema = z.object({
      search: z.string(),
      page: z.coerce.number().default(1), // Default value test
    });

    it('calls next() and updates req.query on success', async () => {
      const req = makeReq({ query: { search: 'hello' } });
      const res = makeRes();

      const middleware = Validate.query(schema);
      await middleware(req, res, next);

      expect(next).toHaveBeenCalledTimes(1);
      // Ensures Zod applied the default value and attached it to req.query
      expect(req.query).toEqual({ search: 'hello', page: 1 });
    });

    it('returns 400 on failure', async () => {
      const req = makeReq({ query: {} }); // Missing required search
      const res = makeRes();

      const middleware = Validate.query(schema);
      await middleware(req, res, next);

      expect(next).not.toHaveBeenCalled();
      expect(res.status).toHaveBeenCalledWith(400);
    });
  });

  describe('Error Message Sanitization', () => {
    it('strips special characters from the Zod error message', async () => {
      // Create a schema that triggers a specific, heavily punctuated error message
      const schema = z.object({
        username: z.string().min(5, { message: 'Invalid! Username must be >= 5 chars.' }),
      });

      const req = makeReq({ body: { username: 'bob' } });
      const res = makeRes();

      const middleware = Validate.body(schema);
      await middleware(req, res, next);

      expect(res.status).toHaveBeenCalledWith(400);

      // The original message: "Invalid! Username must be >= 5 chars."
      // The expected message: "Invalid Username must be  5 chars" (punctuation stripped)
      expect(res.json).toHaveBeenCalledWith({
        success: false,
        message: 'Invalid Username must be  5 chars',
      });
    });
  });
});
